### ISSUE TITLE
Wrong FastCGI request header

### ISSUE THREAD

**Issue by hitok** [Gedweb/rust-gfcgi#1]
Hi,

I have some issue with basic example - thread 'main' panicked at 'Wron FastCGI request header'

Env: 
Windows 10
Nginx 1.10
Rust 1.14

Nginx conf:
server {
  ...
   location / {
      fastcgi_pass 127.0.0.1:4128;
      include fastcgi_params;
    }
  ...
}

Additional debug info:

//let h = http::Request::fcgi_header(self.stream);
// println!("{:?}", h);
Header { version: 1, type_: 1, request_id: 1, content_length: 8, padding_length: 0, reserved: [0] }
Header { version: 1, type_: 4, request_id: 1, content_length: 827, padding_length: 5, reserved: [0] }
Header { version: 0, type_: 0, request_id: 0, content_length: 1, padding_length: 4, reserved: [0] }

**Comment by Gedweb** [comment]
Hi, thanks for your reply.
I think two problem can be related with it
1) `FCGI_GET_VALUES`, `FCGI_GET_VALUES_RESULT`
    at current time, headers not supported, but can be received any time. Planned to release coming soon.
2) `padding_length` - not released and need learn how it work

**Comment by Gedweb** [comment]
`padding_length` is a reason of panic.
Fixed. Successfully tested on nginx.
